version: '2'

services:
    retsus:
        container_name: RETSUS
        build:
            context: ./Dockerfiles
            dockerfile: Dockerfile_Laravel
        volumes:
            - /mnt/data/apps:/apps
        environment:
            - "TZ=America/Sao_Paulo"
        networks:
            - code-network
    sabia:
        container_name: SABIA
        build:
            context: ./Dockerfiles
            dockerfile: Dockerfile_Laravel
        volumes:
            - /mnt/data/apps:/apps
        environment:
            - "TZ=America/Sao_Paulo"
        networks:
            - code-network
    db:
        image: postgres
        networks:
            - code-network
    redis:
        image: redis
        networks:
            - code-network
    web:
        container_name: NGINX
        build:
            context: ./Dockerfiles
            dockerfile: Dockerfile_Nginx
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - /mnt/data/apps:/apps
            - ./nginx_vhosts:/etc/nginx/conf.d/
            - ./letsencrypt:/etc/letsencrypt
            - ./nginx_snippets:/etc/nginx/snippets
        environment:
            - "TZ=America/Sao_Paulo"
        networks:
            - code-network
        depends_on:
            - retsus

networks:
    code-network:
        driver: bridge
